services:
  db:
    image: postgres
    container_name: octopus_db
    restart: always
    environment:
      POSTGRES_USER: octopus_test
      POSTGRES_PASSWORD: octopus_test
      POSTGRES_DB: octopus_v2
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      # point to 5422
      - "5422:5432"