version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: octopus_test
      POSTGRES_PASSWORD: octopus_test
      POSTGRES_DB: octopus_v2
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432